### ISSUE TITLE
docker-compose example?

### ISSUE THREAD

**Issue by geoffyuen** [ustwo/docker-browser-sync#3]
I managed to get a test working using this in my docker-compose.yml:

```
bs:
  image: ustwo/browser-sync
  command: browser-sync start --help
  ports:
      - 3000:3000
```

And I get the expected help text output to the terminal. But when I change the command to:

```
bs:
  image: ustwo/browser-sync
  command: browser-sync start --files .
  ports:
      - 3000:3000
```

I get:

```
bs_1  | module.js:471
bs_1  |     throw err;
bs_1  |     ^
bs_1  |
bs_1  | Error: Cannot find module '../lib/cli/command.browser-sync'
bs_1  |     at Function.Module._resolveFilename (module.js:469:15)
bs_1  |     at Function.Module._load (module.js:417:25)
bs_1  |     at Module.require (module.js:497:17)
bs_1  |     at require (internal/module.js:20:19)
bs_1  |     at handleCli (/usr/local/lib/node_modules/browser-sync/bin/browser-sync.js:40:12)
bs_1  |     at handleIncoming (/usr/local/lib/node_modules/browser-sync/bin/browser-sync.js:90:5)
bs_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/browser-sync/bin/browser-sync.js:27:9)
bs_1  |     at Module._compile (module.js:570:32)
bs_1  |     at Object.Module._extensions..js (module.js:579:10)
bs_1  |     at Module.load (module.js:487:32)
browsersynctest_bs_1 exited with code 1
```

I'm not sure what I'm doing wrong here.
