### ISSUE TITLE
Browser doesn't refresh when making edits on shared volume on host

### ISSUE THREAD

**Issue by jtcmedia** [ustwo/docker-browser-sync#4]
This is a great idea, but doesn't work as intended. Here's my docker compose file:
```
version: "3"
services:
  node:
    container_name: node
    image: node:6
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=8001
      - NODE_ENV=development
    ports:
      - "8001:8001"
    volumes:
      - ./app:/home/node/app
    command: "nodemon -L"
  bs:
    image: ustwo/browser-sync
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - node
    volumes:
      - ./app:/source
    command: "start --proxy node:8001 --no-open --files '**/*.pug, **/*.css, **/*.js'"
```    
Everything works, Browsersync says its connected, but any edits made in the shared volume on the host doesn't cause a browser refresh. If I log into the container and make edits in the volume there, it works as intended.
